server:
  port: 8150
  servlet:
    context-path: /service-client
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/db_service-client
    username: postgres
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

